### PR TITLE
 darwin: Fix uiMenuItem enable/disable and resulting segfaults. 

### LINKED ISSUE #230: Menu items can NOT be disabled and cause segfault on macOS
`uiMenuItemDisable` does not work on macOS.
And the default menu items (e.g. `Preferences...`) are not disabled.
Clicking them causes segfault because they have null pointers as `uiMenuItem`.
menuitems

### PR DESCRIPTION
**Pull request by szanni**
Fix the regression introduced in https://github.com/libui-ng/libui-ng/commit/9e08072fc207d8392075e0c2c8b9c8fa11583bb2 which makes disabling uiMenuItems impossible on macOS.

Nonexistent system menu items are now disabled by default again. And I removed some unreachable code and hardened the onClick handler against future segfaults.

I removed the weird literature around OS X menu handling in the comment, as I did not find it helpful in understanding what was happening in the slightest. Happy to reintroduce that though, if desired.

Fixes #230

### CODE REVIEW

**Comment by szanni** [comment]
Fixed the comment in the force-push.

File: darwin/menu.m [hunk 1]
```diff
@@ -77,6 +80,18 @@ - (void)setUiMenuItem:(uiMenuItem *)i
 	self->item = i;
 }
 
+// Manually enable/disable menu items
+- (BOOL)validateMenuItem:(NSMenuItem *)item
```
Comment (cody271) [inline darwin/menu.m:84]:
```suggestion
- (BOOL)validateMenuItem:(NSMenuItem *)menuItem
```

File: darwin/menu.m [hunk 2]
```diff
@@ -77,6 +80,18 @@ - (void)setUiMenuItem:(uiMenuItem *)i
...
+{
+	uiprivMenuItem *i = (uiprivMenuItem *)item;
```
Comment (cody271) [inline darwin/menu.m:86]:
```suggestion
	uiprivMenuItem *i = (uiprivMenuItem *)menuItem;
```

File: darwin/menu.m (hunk 1 above)
Comment (cody271) [inline darwin/menu.m:84]:
```diff
diff --git a/darwin/uipriv_darwin.h b/darwin/uipriv_darwin.h
index 2046e36f..6d79a454 100644
--- a/darwin/uipriv_darwin.h
+++ b/darwin/uipriv_darwin.h
@@ -33,6 +33,7 @@ void uiprivNSTextFieldSetStyleSearchEntry(NSTextField *t);
 @public
        uiMenuItem *item;
 }
+- (BOOL)validateMenuItem:(NSMenuItem *)menuItem;
 @end
 @interface uiprivMenuManager : NSObject {
        BOOL hasQuit;
@@ -44,8 +45,6 @@ void uiprivNSTextFieldSetStyleSearchEntry(NSTextField *t);
 @property (unsafe_unretained) uiprivMenuItem *quitItem;
 @property (unsafe_unretained) uiprivMenuItem *preferencesItem;
 @property (unsafe_unretained) uiprivMenuItem *aboutItem;
-// NSMenuValidation is only informal
-- (BOOL)validateMenuItem:(NSMenuItem *)item;
 - (NSMenu *)makeMenubar;
 - (BOOL)finalized;
 - (void)finalize;
```

**Review by cody271 — COMMENTED** [review]
Fixes for some compiler warnings:
```shell
../darwin/menu.m:86:40: warning: local declaration of 'item' hides instance variable [-Wshadow-ivar]
        uiprivMenuItem *i = (uiprivMenuItem *)item;
                                              ^
../darwin/menu.m:97:17: warning: method definition for 'validateMenuItem:' not found [-Wincomplete-implementation]
@implementation uiprivMenuManager
                ^
../darwin/uipriv_darwin.h:48:1: note: method 'validateMenuItem:' declared here
- (BOOL)validateMenuItem:(NSMenuItem *)item;
^
2 warnings generated.
../darwin/menu.m:86:40: warning: local declaration of 'item' hides instance variable [-Wshadow-ivar]
        uiprivMenuItem *i = (uiprivMenuItem *)item;
                                              ^
../darwin/menu.m:97:17: warning: method definition for 'validateMenuItem:' not found [-Wincomplete-implementation]
@implementation uiprivMenuManager
                ^
../darwin/uipriv_darwin.h:48:1: note: method 'validateMenuItem:' declared here
- (BOOL)validateMenuItem:(NSMenuItem *)item;
^
2 warnings generated.
```

**Comment by szanni** [comment]
> Fixes for some compiler warnings:

Thanks for catching those! Fixed.

**Review by cody271 — APPROVED** [review]
LGTM
